//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrderMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOrderMaster()
        {
            this.Invoice = new HashSet<Invoice>();
            this.PaymentMaster = new HashSet<PaymentMaster>();
            this.RSSMaster = new HashSet<RSSMaster>();
            this.SampleReceiveList = new HashSet<SampleReceiveList>();
            this.JobOrderDetails = new HashSet<JobOrderDetails>();
        }
    
        public long JobOrderMasterID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<long> FKQuotationMasterID { get; set; }
        public int FKCustomerID { get; set; }
        public string LPONumber { get; set; }
        public Nullable<decimal> ReceiveCreditLimit { get; set; }
        public Nullable<decimal> ReportCreditLimit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int FKProjectID { get; set; }
        public string Remarks { get; set; }
        public bool IsClosed { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UnpaidReceiveLimit { get; set; }
        public string JobOrderNumber { get; set; }
        public int StatusID { get; set; }
        public bool IsReporting { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string ContractName { get; set; }
    
        public virtual CustomersList CustomersList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ProjectsList ProjectsList { get; set; }
        public virtual QuotationMaster QuotationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMaster> PaymentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSSMaster> RSSMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleReceiveList> SampleReceiveList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobOrderDetails> JobOrderDetails { get; set; }
    }
}
