//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReporting
    {
        public long TestReportingID { get; set; }
        public long FKSampleReceiveTestID { get; set; }
        public int StatusID { get; set; }
        public int RevisionNo { get; set; }
        public bool IsRevised { get; set; }
        public Nullable<System.DateTime> TestEndingDate { get; set; }
        public Nullable<System.DateTime> ReportingDate { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> SuggestedTestingDate { get; set; }
    
        public virtual SampleReceiveTestList SampleReceiveTestList { get; set; }
    }
}
