//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLateReport
    {
        public long TestReportingID { get; set; }
        public int ReportNumber { get; set; }
        public string SampleNumber { get; set; }
        public string TestName { get; set; }
        public string LabName { get; set; }
        public string StandardNumber { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<System.DateTime> TestEndingDate { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<System.DateTime> SampleReceivedDate { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public int TestRequiredTime { get; set; }
        public string TestDurationStatus { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ReportDuration { get; set; }
        public string ReportDurationStatus { get; set; }
        public Nullable<int> TotalDuration { get; set; }
        public string TotalDurationStatus { get; set; }
        public string CustomerName { get; set; }
        public string ProjectName { get; set; }
        public long FKSampleReceiveTestID { get; set; }
        public int StatusID { get; set; }
        public int RevisionNo { get; set; }
        public bool IsRevised { get; set; }
        public Nullable<int> FKProjectID { get; set; }
        public Nullable<int> FKTestID { get; set; }
        public Nullable<int> FKCustomerID { get; set; }
        public string WorkFormFileName { get; set; }
        public Nullable<System.DateTime> SuggestedTestingDate { get; set; }
        public Nullable<int> FKLabID { get; set; }
        public Nullable<decimal> LatePercentage { get; set; }
        public Nullable<decimal> ReportDurationLatePercentage { get; set; }
        public Nullable<decimal> TotalDurationLatePercentage { get; set; }
    }
}
