//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryLayer.Reports.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceVSAccreditationStatusReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceVSAccreditationStatusReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaboratoryLayer.Reports.Menu.ServiceVSAccreditationStatusReport", typeof(ServiceVSAccreditationStatusReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH TestData AS  (
        ///SELECT 
        ///    &quot;AccreditionList&quot;.&quot;AccreditionName&quot; AS &quot;AccreditationStatus&quot;,
        ///    &quot;TestsList&quot;.&quot;StandardNumber&quot;,
        ///    &quot;LabsList&quot;.&quot;LabName&quot;,
        ///    &quot;TestsList&quot;.&quot;AshghalTestNumber&quot; AS &quot;AshghalNumber&quot;,
        ///    &quot;TestsList&quot;.&quot;ShortName&quot;,
        ///    &quot;TestsList&quot;.&quot;TestName&quot;,
        ///    &quot;TestsList&quot;.&quot;ResultSpecs&quot; AS &quot;AccreditionNo&quot;,
        ///    &quot;pu&quot;.&quot;UnitName&quot;,
        ///    &quot;tp&quot;.&quot;DefaultPrice&quot;,
        ///    &quot;tp&quot;.&quot;MinimumPrice&quot;,
        ///    (SELECT TOP 1 &quot;MaterialsTypes&quot;.&quot;MaterialName&quot; 
        ///     FROM &quot;dbo&quot;.&quot;MaterialsTypes&quot; 
        ///     WHERE &quot;MaterialsType [rest of string was truncated]&quot;;.
        /// </summary>
        public static string customSqlQuery1_Sql {
            get {
                return ResourceManager.GetString("customSqlQuery1.Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERhdGFTZXQgTmFtZT0ic3FsRGF0YVNvdXJjZTEiPjxWaWV3IE5hbWU9IkpvYk9yZGVyRGV0YWlscyI+PEZpZWxkIE5hbWU9IkFjY3JlZGl0YXRpb25TdGF0dXMiIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iU3RhbmRhcmROdW1iZXIiIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iTGFiTmFtZSIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJBc2hnaGFsTnVtYmVyIiBUeXBlPSJTdHJpbmciIC8+PEZpZWxkIE5hbWU9IlNob3J0TmFtZSIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJUZXN0TmFtZSIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJBY2NyZWRpdGlvbk5vIiBUeXBlPSJTdHJpbmciIC8+PEZpZWxkIE5hbWU9IlVuaXROYW1lIiBU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sqlDataSource1_ResultSchemaSerializable {
            get {
                return ResourceManager.GetString("sqlDataSource1.ResultSchemaSerializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point sqlDataSource1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sqlDataSource1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
